### ISSUE TITLE
Irksome run 'systemctl daemon-reload' warning

### ISSUE THREAD

**Issue by sigmdel** [agambier/domoticz_addons#1]
Thank you @agambler for the elegant solution.

However there's a persistent warning about the need to reload daemons:

```
~ $ sudo systemctl status domoticz.service
**Warning:** The unit file, source configuration file or drop-ins of domoticz.service changed on disk. Run 'systemctl daemon-reload' to reload units.
```

Any way of getting rid of the warning ? 

This is purely cosmetic. While the warning is shown when restarting the domoticz.service, the latter restarts without problem.

**Comment by agambier** [comment]
Sorry for the late reply.

No I don't kown how to get rid of that warning. Sorry !

**Comment by sigmdel** [comment]
That's all right. My OCD just got the better of me. Besides, I have since noticed that another Drop-In service displays the same behaviour. I take that as a hint that your unit file is not the "culprit".
Thanks again.
